blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/ivi374forivi/fetch-familiar-friends/discussions
    about: Ask questions and discuss ideas with the community
